version: 1.0.{build}
configuration: Debug
platform: x86
before_build:
- cmd: cd .\api\src && nuget restore
build:
  verbosity: minimal
after_build:
- ps: >-
    $dir = "c:\projects\box9d-leds-manager"


    Set-Location "$($dir)\web"

    npm install

    & "$($dir)\web\copyfiles.ps1"

    & "$($dir)\GenerateArtifacts.ps1"
artifacts:
- path: build