version: 1.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
before_build:
- cmd: cd .\api\src && nuget restore
after_build:
- ps: >-
    cd .\web && npm install

    cd .\web && copyfiles.ps1

    .\GenerateArtifacts.ps1